/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAdSlotNFT } from "./IAdSlotNFT";
export type { MetaShiftAdManager } from "./MetaShiftAdManager";
