/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MetaShiftAdManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "HOST_SHARE_BP"
      | "TREASURY_SHARE_BP"
      | "VIEWER_SHARE_BP"
      | "adSlotNFT"
      | "campaigns"
      | "createCampaign"
      | "fundCampaign"
      | "nextCampaignId"
      | "owner"
      | "payView"
      | "renounceOwnership"
      | "setCampaignStatus"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "viewPaid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignFunded"
      | "CampaignStatus"
      | "OwnershipTransferred"
      | "ViewPaid"
  ): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "HOST_SHARE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_SHARE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VIEWER_SHARE_BP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "adSlotNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BigNumberish, string, string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundCampaign",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCampaignId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payView",
    values: [BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "viewPaid", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "HOST_SHARE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_SHARE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VIEWER_SHARE_BP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "adSlotNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCampaignId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payView", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "viewPaid", data: BytesLike): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    advertiser: AddressLike,
    slotId: BigNumberish
  ];
  export type OutputTuple = [id: bigint, advertiser: string, slotId: bigint];
  export interface OutputObject {
    id: bigint;
    advertiser: string;
    slotId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignFundedEvent {
  export type InputTuple = [id: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [id: bigint, amount: bigint];
  export interface OutputObject {
    id: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignStatusEvent {
  export type InputTuple = [id: BigNumberish, active: boolean];
  export type OutputTuple = [id: bigint, active: boolean];
  export interface OutputObject {
    id: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ViewPaidEvent {
  export type InputTuple = [
    id: BigNumberish,
    viewId: BytesLike,
    host: AddressLike,
    viewer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    viewId: string,
    host: string,
    viewer: string,
    amount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    viewId: string;
    host: string;
    viewer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MetaShiftAdManager extends BaseContract {
  connect(runner?: ContractRunner | null): MetaShiftAdManager;
  waitForDeployment(): Promise<this>;

  interface: MetaShiftAdManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  HOST_SHARE_BP: TypedContractMethod<[], [bigint], "view">;

  TREASURY_SHARE_BP: TypedContractMethod<[], [bigint], "view">;

  VIEWER_SHARE_BP: TypedContractMethod<[], [bigint], "view">;

  adSlotNFT: TypedContractMethod<[], [string], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, string, bigint, bigint, boolean] & {
        advertiser: string;
        slotId: bigint;
        creativeURI: string;
        clickURL: string;
        paymentToken: string;
        budget: bigint;
        pricePerView: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [
      slotId: BigNumberish,
      creativeURI: string,
      clickURL: string,
      paymentToken: AddressLike,
      pricePerView: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  fundCampaign: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  nextCampaignId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payView: TypedContractMethod<
    [id: BigNumberish, viewId: BytesLike, viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCampaignStatus: TypedContractMethod<
    [id: BigNumberish, active_: boolean],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [treasury_: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  viewPaid: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "HOST_SHARE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREASURY_SHARE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VIEWER_SHARE_BP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adSlotNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, string, bigint, bigint, boolean] & {
        advertiser: string;
        slotId: bigint;
        creativeURI: string;
        clickURL: string;
        paymentToken: string;
        budget: bigint;
        pricePerView: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      slotId: BigNumberish,
      creativeURI: string,
      clickURL: string,
      paymentToken: AddressLike,
      pricePerView: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundCampaign"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "nextCampaignId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payView"
  ): TypedContractMethod<
    [id: BigNumberish, viewId: BytesLike, viewer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCampaignStatus"
  ): TypedContractMethod<
    [id: BigNumberish, active_: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[treasury_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "viewPaid"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignFunded"
  ): TypedContractEvent<
    CampaignFundedEvent.InputTuple,
    CampaignFundedEvent.OutputTuple,
    CampaignFundedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignStatus"
  ): TypedContractEvent<
    CampaignStatusEvent.InputTuple,
    CampaignStatusEvent.OutputTuple,
    CampaignStatusEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ViewPaid"
  ): TypedContractEvent<
    ViewPaidEvent.InputTuple,
    ViewPaidEvent.OutputTuple,
    ViewPaidEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,address,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignFunded(uint256,uint256)": TypedContractEvent<
      CampaignFundedEvent.InputTuple,
      CampaignFundedEvent.OutputTuple,
      CampaignFundedEvent.OutputObject
    >;
    CampaignFunded: TypedContractEvent<
      CampaignFundedEvent.InputTuple,
      CampaignFundedEvent.OutputTuple,
      CampaignFundedEvent.OutputObject
    >;

    "CampaignStatus(uint256,bool)": TypedContractEvent<
      CampaignStatusEvent.InputTuple,
      CampaignStatusEvent.OutputTuple,
      CampaignStatusEvent.OutputObject
    >;
    CampaignStatus: TypedContractEvent<
      CampaignStatusEvent.InputTuple,
      CampaignStatusEvent.OutputTuple,
      CampaignStatusEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ViewPaid(uint256,bytes32,address,address,uint256)": TypedContractEvent<
      ViewPaidEvent.InputTuple,
      ViewPaidEvent.OutputTuple,
      ViewPaidEvent.OutputObject
    >;
    ViewPaid: TypedContractEvent<
      ViewPaidEvent.InputTuple,
      ViewPaidEvent.OutputTuple,
      ViewPaidEvent.OutputObject
    >;
  };
}
