/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as metaShiftAdManagerSol from "./MetaShiftAdManager.sol";
export type { metaShiftAdManagerSol };
export type { AdSlotNFT } from "./AdSlotNFT";
