/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAdSlotNFT,
  IAdSlotNFTInterface,
} from "../../../contracts/MetaShiftAdManager.sol/IAdSlotNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAdSlotNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IAdSlotNFTInterface {
    return new Interface(_abi) as IAdSlotNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAdSlotNFT {
    return new Contract(address, _abi, runner) as unknown as IAdSlotNFT;
  }
}
